/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/register": {
    post: operations["register"];
  };
  "/v1/login": {
    post: operations["login"];
  };
  "/v1/user/recipes/create": {
    post: operations["createRecipe"];
  };
  "/v1/user/recipes/list": {
    get: operations["listUserRecipes"];
  };
  "/v1/recipes": {
    get: operations["listRecipes"];
  };
  "/v1/recipes/{recipeId}": {
    get: operations["getRecipe"];
  };
  "/v1/users": {
    get: operations["listUsers"];
  };
}

export interface components {
  schemas: {
    RegisterBody: {
      name: string;
      email: string;
      password: string;
      about: string;
    };
    RegisterSuccess: {
      name: string;
      email: string;
    };
    LoginSuccess: {
      token: string;
    };
    CreateRecipeBody: {
      title: string;
      summary: string;
      authorsLifeStory: string;
      ingredients: string[];
      instructions: string[];
    };
    CreateRecipeSuccess: {
      id: string;
    };
    ListUserRecipesSuccess: {
      id: string;
      title: string;
      summary: string;
    };
    ListRecipesSuccess: {
      id: string;
      title: string;
      summary: string;
      userId: string;
      userName: string;
      userAbout: string;
    };
    GetRecipeSuccess: {
      id: string;
      title: string;
      summary: string;
      authorsLifeStory: string;
      ingredients: string[];
      instructions: string[];
      userId: string;
      userName: string;
      userAbout: string;
    };
    ListUsersSuccess: {
      id: string;
      name: string;
      about: string;
    }[];
    InternalError: {
      message: "internal error";
    };
    ValidationError: {
      message: "validation error";
      errors: string[];
    };
    AuthorisationError: {
      message: string;
      errors: string[];
    };
    GenericError: {
      message: string;
      errors: string[];
    };
  };
  parameters: {
    /** Id of the user to filter on */
    listRecipesUserParameter: string;
    /** String to filter receipt title on */
    listRecipesTitleParameter: string;
    /** Id of the recipe being accessed */
    recipeIdParameter: string;
    /** The name of the user to search for */
    listUsersNameParameter: string;
  };
}

export interface operations {
  register: {
    responses: {
      /** OK */
      201: {
        content: {
          "application/json": components["schemas"]["RegisterSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["AuthorisationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
  };
  login: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["LoginSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
  };
  createRecipe: {
    responses: {
      /** OK */
      201: {
        content: {
          "application/json": components["schemas"]["CreateRecipeSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["AuthorisationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRecipeBody"];
      };
    };
  };
  listUserRecipes: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CreateRecipeSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
  };
  listRecipes: {
    parameters: {
      query: {
        /** Id of the user to filter on */
        userId?: components["parameters"]["listRecipesUserParameter"];
        /** String to filter receipt title on */
        title?: components["parameters"]["listRecipesTitleParameter"];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListRecipesSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
  };
  getRecipe: {
    parameters: {
      path: {
        /** Id of the recipe being accessed */
        recipeId: components["parameters"]["recipeIdParameter"];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["GetRecipeSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query: {
        /** The name of the user to search for */
        name?: components["parameters"]["listUsersNameParameter"];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListUsersSuccess"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** Internal Error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalError"];
        };
      };
    };
  };
}

export interface external {}
